name: nowa_sample
description: A new Nowa project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  nowa_runtime: ^0.0.38
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.7
  provider: ^6.1.1
  shared_preferences: ^2.2.3
  dio: ^5.5.0+1
  youtube_player_iframe_plus: ^2.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
